### ISSUE TITLE
ftp connection error 

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/ont_tutorial_transcriptome#7]
I am struggling to get transcriptome snakemake to run as it seems there is a hang when connecting to Ensembl. I checked and it seems they have recently mirrored through ebi.ac.uk as some severs will be physically moved. I also tried editing config with updated links using ebi mirror. it has same error. 

```
Traceback (most recent call last):
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/urllib3/connection.py", line 334, in connect
    conn = self._new_conn()
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f36830ada50>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ftp.ensembl.org', port=443): Max retries exceeded with url: /pub/release-95/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36830ada50>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/__init__.py", line 633, in snakemake
    keepincomplete=keep_incomplete,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/workflow.py", line 565, in execute
    dag.init()
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 168, in init
    job = self.update([job], progress=progress)
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 693, in update
    progress=progress,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 769, in update_
    progress=progress,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 693, in update
    progress=progress,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 769, in update_
    progress=progress,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 693, in update
    progress=progress,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 769, in update_
    progress=progress,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 693, in update
    progress=progress,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 769, in update_
    progress=progress,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 693, in update
    progress=progress,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 769, in update_
    progress=progress,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 693, in update
    progress=progress,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 757, in update_
    if not file.exists:
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/io.py", line 262, in exists
    return self.exists_remote
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/io.py", line 135, in wrapper
    v = func(self, *args, **kwargs)
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/io.py", line 314, in exists_remote
    return self.remote_object.exists()
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/remote/HTTP.py", line 159, in exists
    with self.httpr(verb="HEAD") as httpr:
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/remote/HTTP.py", line 152, in httpr
    r = requests.head(url, *args_to_use, **kwargs_to_use)
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/requests/api.py", line 101, in head
    return request('head', url, **kwargs)
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ftp.ensembl.org', port=443): Max retries exceeded with url: /pub/release-95/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f36830ada50>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

**Edit to config to include mirror sites instead** 

```
transcriptome: "http://ftp.ebi.ac.uk/ensemblorg/pub/release-99/fasta/mus_musculus/cdna/Homo_sapiens.GRCm38.cdna.all.fa.gz"

annotation: "http://ftp.ebi.ac.uk/ensemblorg/pub/release-99/gtf/homo_sapiens/Homo_sapiens.GRCh38.99.gtf.gz"
```

```
Traceback (most recent call last):
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/urllib3/connection.py", line 334, in connect
    conn = self._new_conn()
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fdc40a0e550>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ftp.ebi.ac.uk', port=443): Max retries exceeded with url: /ensemblorg/pub/release-99/fasta/mus_musculus/cdna/Homo_sapiens.GRCm38.cdna.all.fa.gz (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdc40a0e550>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/__init__.py", line 633, in snakemake
    keepincomplete=keep_incomplete,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/workflow.py", line 565, in execute
    dag.init()
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 168, in init
    job = self.update([job], progress=progress)
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 693, in update
    progress=progress,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 769, in update_
    progress=progress,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 693, in update
    progress=progress,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 769, in update_
    progress=progress,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 693, in update
    progress=progress,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 769, in update_
    progress=progress,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 693, in update
    progress=progress,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 769, in update_
    progress=progress,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 693, in update
    progress=progress,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 769, in update_
    progress=progress,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 693, in update
    progress=progress,
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/dag.py", line 757, in update_
    if not file.exists:
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/io.py", line 262, in exists
    return self.exists_remote
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/io.py", line 135, in wrapper
    v = func(self, *args, **kwargs)
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/io.py", line 314, in exists_remote
    return self.remote_object.exists()
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/remote/HTTP.py", line 159, in exists
    with self.httpr(verb="HEAD") as httpr:
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/snakemake/remote/HTTP.py", line 152, in httpr
    r = requests.head(url, *args_to_use, **kwargs_to_use)
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/requests/api.py", line 101, in head
    return request('head', url, **kwargs)
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/minion/miniconda3/envs/transcriptome_tutorial/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ftp.ebi.ac.uk', port=443): Max retries exceeded with url: /ensemblorg/pub/release-99/fasta/mus_musculus/cdna/Homo_sapiens.GRCm38.cdna.all.fa.gz (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fdc40a0e550>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

From terminal I can wget each file from the URL provided so I am unsure what the issue is.

Is there a way to provide the file path to already downloaded references?

**Comment by PingpingZheng** [comment]
You may try to comment out lines 66-81 in `Snakefile`, and also change the directories of "transcriptome:" and "annotation:" in the config.yml file to your local file directories.

**Comment by callumparr** [comment]
> You may try to comment out lines 66-81 in `Snakefile`, and also change the directories of "transcriptome:" and "annotation:" in the config.yml file to your local file directories.

hey thanks, I will try this nice. Sorry late reply. Thank you for your help

**Comment by callumparr** [comment]
> You may try to comment out lines 66-81 in `Snakefile`, and also change the directories of "transcriptome:" and "annotation:" in the config.yml file to your local file directories.

Worked a charm
